# Generated by Django 5.2.7 on 2026-01-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='talle',
            options={'verbose_name': 'Talle', 'verbose_name_plural': 'Talles'},
        ),
    ]
