# Generated by Django 5.2.7 on 2026-01-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
