# Generated by Django 5.2.7 on 2026-01-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='external_id',
        ),
    ]
