# Generated by Django 5.2.7 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_producto_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
