# Generated by Django 5.2.7 on 2026-02-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_imagenproducto_es_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
