# Generated by Django 5.2.7 on 2026-02-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_categoria_actualizado_categoria_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la categoría en la página principal (tamaño recomendado: 600x400px)', null=True, upload_to='categorias/'),
        ),
    ]
