# Generated by Django 5.2.7 on 2026-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_pagos', '0002_remove_itempedido_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nombre_producto',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
