# Generated by Django 5.2.8 on 2025-12-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_pagos', '0002_pedido_cliente_email_pedido_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
