# Generated by Django 5.2.7 on 2026-02-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_pagos', '0002_alter_itempedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
