# Generated by Django 5.2.7 on 2026-01-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '__first__'),
        ('pedidos_pagos', '0003_remove_pago_cantidad_remove_pago_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='carrito.carrito'),
        ),
    ]
