# Generated by Django 5.2.8 on 2025-12-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilempleado',
            options={},
        ),
    ]
